# -*- coding: utf-8 -*-
"""MCA_train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14_Pa3ywfTYBVwBXBKqZsTfCf8uwOBOXx
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install wandb -qU
import wandb

wandb.login()

import sys
sys.path.append('/content/drive/MyDrive/Colab Notebooks/CVIP_LAB/UAV/MemLoTrack')
sys.path.append("/content/drive/MyDrive/Colab Notebooks/CVIP_LAB/UAV/MCATrack")

!unzip -q "/content/drive/MyDrive/Colab Notebooks/CVIP_LAB/UAV/MemLoTrack/Anti-UAV410.zip" -d /content/data

!rm -rf /content/data/__MACOSX

import os
import sys
import cv2
import torch
from network_MCA_mac import MCATracker

import os
import cv2
import json
import torch
import random
import numpy as np
from torch.utils.data import Dataset, DataLoader

import glob

import subprocess

class AntiUAVDataset(Dataset):
    def __init__(self, root_dir: str, split: str = "train"):
        self.split_dir = os.path.join(root_dir, split)
        self.video_seqs = []

        if not os.path.exists(self.split_dir):
            return

        video_names = [d for d in sorted(os.listdir(self.split_dir))
                       if os.path.isdir(os.path.join(self.split_dir, d))]

        for video_name in video_names:
            seq_dir = os.path.join(self.split_dir, video_name)
            label_path = os.path.join(seq_dir, "IR_label.json")

            if not os.path.exists(label_path):
                continue

            img_paths = sorted([os.path.join(seq_dir, f) for f in os.listdir(seq_dir)
                               if f.lower().endswith(('.jpg', '.jpeg', '.png'))])

            if len(img_paths) > 0:
                with open(label_path, "r") as f:
                    label_data = json.load(f)

                min_len = min(len(img_paths), len(label_data['exist']))
                self.video_seqs.append({
                    "video_name" : video_name,
                    "img_paths" : img_paths[:min_len],
                    "exist" : label_data['exist'][:min_len],
                    "gt_rect" : label_data['gt_rect'][:min_len]
                })

    def __len__(self):
        return len(self.video_seqs) * 10

    def __getitem__(self, idx):
        actual_idx = idx % len(self.video_seqs)
        seq = self.video_seqs[actual_idx]
        img_paths = seq["img_paths"]
        exists = seq["exist"]
        gt_rects = seq["gt_rect"]

        valid_indices = [i for i, e in enumerate(exists) if e == 1]

        if len(valid_indices) < 2:
            return self.__getitem__((idx + 1) % len(self.video_seqs))

        init_idx = valid_indices[0]
        search_valid_indices = [i for i in valid_indices if i > init_idx]

        if not search_valid_indices:
            return self.__getitem__((idx + 1) % len(self.video_seqs))

        search_idx = random.choice(search_valid_indices)
        prev_idx = search_idx - 1

        init_frame = cv2.imread(img_paths[init_idx])
        prev_frame = cv2.imread(img_paths[prev_idx])
        search_frame = cv2.imread(img_paths[search_idx])

        target_sz = (255, 255)

        init_frame=cv2.resize(init_frame, target_sz)
        prev_frame=cv2.resize(prev_frame, target_sz)
        search_frame=cv2.resize(search_frame, target_sz)

        init_bbox = torch.tensor(gt_rects[init_idx], dtype=torch.float32)
        search_bbox = torch.tensor(gt_rects[search_idx], dtype=torch.float32)

        return {
            'video_name': seq["video_name"],
            'init_frame': init_frame,
            'init_bbox': init_bbox,
            'prev_frame': prev_frame,
            'search_frame': search_frame,
            'search_gt_bbox': search_bbox
        }

from torchvision.ops import box_iou

def cxcywh_to_xyxy(boxes):
    """
    (center_x, center_y, width, height) -> (x1, y1, x2, y2) 변환
    boxes: [N, 4] 텐서
    """
    cx, cy, w, h = boxes.unbind(-1)
    x1 = cx - 0.5 * w
    y1 = cy - 0.5 * h
    x2 = cx + 0.5 * w
    y2 = cy + 0.5 * h
    return torch.stack((x1, y1, x2, y2), dim=-1)

def compute_loss(class_scores, pred_deltas, base_anchors, gt_bbox, device):
    """
    class_scores: [1, 2028, 2] (모델이 예측한 분류 점수)
    pred_deltas:  [1, 2028, 4] (모델이 예측한 좌표 델타)
    base_anchors: [2028, 4] (고정된 기본 앵커 cx, cy, w, h)
    gt_bbox:      [4] (정답 박스 x_left, y_top, w, h) - Anti-UAV 데이터셋 기준
    """
    # 1. 차원 맞추기 (Batch 차원 제거)
    class_scores = class_scores.squeeze(0) # [2028, 2]
    pred_deltas = pred_deltas.squeeze(0)   # [2028, 4]

    # 2. GT Box 형태 변환: [x_left, y_top, w, h] -> [cx, cy, w, h]
    gt_x, gt_y, gt_w, gt_h = gt_bbox
    gt_cx = gt_x + gt_w / 2.0
    gt_cy = gt_y + gt_h / 2.0
    gt_cxcywh = torch.tensor([[gt_cx, gt_cy, gt_w, gt_h]], dtype=torch.float32, device=device)

    # 3. IoU 계산을 위해 양쪽 모두 [x1, y1, x2, y2] 형태로 변환
    anchors_xyxy = cxcywh_to_xyxy(base_anchors)
    gt_xyxy = cxcywh_to_xyxy(gt_cxcywh)

    # [2028, 1] 크기의 IoU 텐서가 나옵니다.
    ious = box_iou(anchors_xyxy, gt_xyxy).squeeze(1)

    # 4. Target Assignment (라벨링)
    # 기본적으로 모두 -1 (Ignore)로 초기화
    labels = torch.full((2028,), -1, dtype=torch.long, device=device)

    # IoU < 0.3 이면 배경(0)
    labels[ious < 0.3] = 0
    # IoU >= 0.6 이면 진짜 객체(1)
    labels[ious >= 0.6] = 1

    # 만약 0.6을 넘는 앵커가 하나도 없다면? 가장 IoU가 높은 녀석 하나라도 1로 만들어줍니다! (안전 장치)
    if (labels == 1).sum() == 0:
        max_iou_idx = torch.argmax(ious)
        labels[max_iou_idx] = 1

    # 5. Regression Target 계산 (Encoding) - 역 디코딩 공식
    anchor_cx, anchor_cy, anchor_w, anchor_h = base_anchors.unbind(dim=1)

    # log 안이 음수가 되는 것을 막기 위해 클리핑 (아주 작은 값 더하기)
    eps = 1e-6
    target_dx = (gt_cx - anchor_cx) / anchor_w
    target_dy = (gt_cy - anchor_cy) / anchor_h
    target_dw = torch.log(gt_w / (anchor_w + eps))
    target_dh = torch.log(gt_h / (anchor_h + eps))

    target_deltas = torch.stack([target_dx, target_dy, target_dw, target_dh], dim=1) # [2028, 4]

    # 6. 대망의 Loss 계산!
    # 분류 Loss (Ignore인 -1은 무시하고 계산하도록 ignore_index=-1 설정)
    criterion_cls = nn.CrossEntropyLoss(ignore_index=-1)
    loss_cls = criterion_cls(class_scores, labels)

    # 회귀 Loss (라벨이 1인 진짜 앵커들에 대해서만 좌표 오차를 계산!)
    pos_indices = (labels == 1)
    if pos_indices.sum() > 0:
        criterion_reg = nn.SmoothL1Loss()
        loss_reg = criterion_reg(pred_deltas[pos_indices], target_deltas[pos_indices])
    else:
        loss_reg = torch.tensor(0.0, device=device, requires_grad=True)

    # 분류와 회귀 Loss를 더함 (회귀 쪽에 가중치를 주는 경우도 많습니다)
    total_loss = loss_cls + (1.0 * loss_reg)

    return total_loss, loss_cls, loss_reg

import torch.optim as optim
import torch.nn as nn
from tqdm import tqdm

def train_and_val(model, train_loader, val_loader, epochs, device, project_name="MCA_Track_UAV"):
    # 1. WandB 프로젝트 시작 (실험 이름 설정)
    wandb.init(
        project=project_name,
        config={
            "learning_rate": 1e-4,
            "architecture": "MCATracker",
            "dataset": "Anti-UAV410",
            "epochs": epochs,
        }
    )

    optimizer = optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-4)

    for epoch in range(epochs):
        model.train()
        train_loss = 0.0

        print(f"\nEpoch {epoch+1}/{epochs} [Train]")
        pbar = tqdm(train_loader)
        for batch in pbar:
            optimizer.zero_grad()

            init_frame = batch['init_frame'][0].numpy()
            init_bbox = batch['init_bbox'][0].numpy()
            search_frame = batch['search_frame'][0].numpy()
            gt_bbox = batch['search_gt_bbox'][0].to(device)

            model.init(init_frame, init_bbox)
            cls_scores, reg_deltas, base_anchors = model.train_track(search_frame, init_bbox)

            loss, l_cls, l_reg = compute_loss(cls_scores, reg_deltas, base_anchors, gt_bbox, device)

            if torch.isinf(loss) or torch.isnan(loss):
                print(f"INF Loss Found -> skipping..{loss.item()}")
                continue

            loss.backward()
            optimizer.step()

            current_loss = loss.item()
            train_loss += current_loss

            wandb.log({
                "batch_loss": current_loss,
                "batch_cls_loss": l_cls.item(),
                "batch_reg_loss": l_reg.item()
            })

            pbar.set_description(f"Loss: {current_loss:.4f}")

        avg_train_loss = train_loss / len(train_loader)

        wandb.log({"epoch": epoch + 1, "avg_train_loss": avg_train_loss})
        print(f"Epoch {epoch+1} Average Loss: {avg_train_loss:.4f}")

        torch.save(model.state_dict(), f'/content/drive/MyDrive/mcatrack_epoch_{epoch+1}.pth')

    wandb.finish()

def test_tracker(model, test_loader, device):
    model.eval()

    test_dir = '/content/data/Anti-UAV410/test'
    if not os.path.exists(test_dir):
        print("테스트 폴더가 없습니다. 경로를 확인해주세요.")
        return

    for seq_name in os.listdir(test_dir):
        seq_path = os.path.join(test_dir, seq_name)
        if not os.path.isdir(seq_path): continue

        img_files = sorted([f for f in os.listdir(seq_path) if f.endswith(('.jpg', '.png'))])

        with open(os.path.join(seq_path, 'IR_label.json'), 'r') as f:
            label_data = json.load(f)
            gt_boxes = label_data['gt_rect']
            exists = label_data['exist']

        first_frame = cv2.imread(os.path.join(seq_path, img_files[0]))
        model.init(first_frame, gt_boxes[0])
        current_bbox = gt_boxes[0]

        for i in range(1, len(img_files)):
            frame = cv2.imread(os.path.join(seq_path, img_files[i]))

            pred_bbox = model.track(frame, current_bbox)
            current_bbox = pred_bbox # 예측한 박스를 다음 탐색 기준으로 업데이트

DATA_DIR = "/content/data/Anti-UAV410"

train_dataset = AntiUAVDataset(root_dir=DATA_DIR, split="train")
val_dataset = AntiUAVDataset(root_dir=DATA_DIR, split="val")

train_loader = DataLoader(train_dataset, batch_size=1, shuffle=True, num_workers=2)
val_loader = DataLoader(val_dataset, batch_size=1, shuffle=False, num_workers=2)

print(f"Train 비디오 개수: {len(train_dataset)}")
print(f"Val 비디오 개수: {len(val_dataset)}")

from torchvision.ops import box_iou

def cxcywh_to_xyxy(boxes):
    """
    (center_x, center_y, width, height) -> (x1, y1, x2, y2) 변환
    boxes: [N, 4] 텐서
    """
    cx, cy, w, h = boxes.unbind(-1)
    x1 = cx - 0.5 * w
    y1 = cy - 0.5 * h
    x2 = cx + 0.5 * w
    y2 = cy + 0.5 * h
    return torch.stack((x1, y1, x2, y2), dim=-1)

def compute_loss(class_scores, pred_deltas, base_anchors, gt_bbox, device):
    """
    class_scores: [1, 2028, 2] (모델이 예측한 분류 점수)
    pred_deltas:  [1, 2028, 4] (모델이 예측한 좌표 델타)
    base_anchors: [2028, 4] (고정된 기본 앵커 cx, cy, w, h)
    gt_bbox:      [4] (정답 박스 x_left, y_top, w, h) - Anti-UAV 데이터셋 기준
    """
    # 1. 차원 맞추기 (Batch 차원 제거)
    class_scores = class_scores.squeeze(0) # [2028, 2]
    pred_deltas = pred_deltas.squeeze(0)   # [2028, 4]

    # 2. GT Box 형태 변환: [x_left, y_top, w, h] -> [cx, cy, w, h]
    gt_x, gt_y, gt_w, gt_h = gt_bbox
    gt_cx = gt_x + gt_w / 2.0
    gt_cy = gt_y + gt_h / 2.0
    gt_cxcywh = torch.tensor([[gt_cx, gt_cy, gt_w, gt_h]], dtype=torch.float32, device=device)

    # 3. IoU 계산을 위해 양쪽 모두 [x1, y1, x2, y2] 형태로 변환
    anchors_xyxy = cxcywh_to_xyxy(base_anchors)
    gt_xyxy = cxcywh_to_xyxy(gt_cxcywh)

    # [2028, 1] 크기의 IoU 텐서가 나옵니다.
    ious = box_iou(anchors_xyxy, gt_xyxy).squeeze(1)

    # 4. Target Assignment (라벨링)
    # 기본적으로 모두 -1 (Ignore)로 초기화
    labels = torch.full((2028,), -1, dtype=torch.long, device=device)

    # IoU < 0.3 이면 배경(0)
    labels[ious < 0.3] = 0
    # IoU >= 0.6 이면 진짜 객체(1)
    labels[ious >= 0.6] = 1

    # 만약 0.6을 넘는 앵커가 하나도 없다면? 가장 IoU가 높은 녀석 하나라도 1로 만들어줍니다! (안전 장치)
    if (labels == 1).sum() == 0:
        max_iou_idx = torch.argmax(ious)
        labels[max_iou_idx] = 1

    # 5. Regression Target 계산 (Encoding) - 역 디코딩 공식
    anchor_cx, anchor_cy, anchor_w, anchor_h = base_anchors.unbind(dim=1)

    # log 안이 음수가 되는 것을 막기 위해 클리핑 (아주 작은 값 더하기)
    eps = 1e-6
    target_dx = (gt_cx - anchor_cx) / anchor_w
    target_dy = (gt_cy - anchor_cy) / anchor_h
    target_dw = torch.log(gt_w / (anchor_w + eps))
    target_dh = torch.log(gt_h / (anchor_h + eps))

    target_deltas = torch.stack([target_dx, target_dy, target_dw, target_dh], dim=1) # [2028, 4]

    # 6. 대망의 Loss 계산!
    # 분류 Loss (Ignore인 -1은 무시하고 계산하도록 ignore_index=-1 설정)
    criterion_cls = nn.CrossEntropyLoss(ignore_index=-1)
    loss_cls = criterion_cls(class_scores, labels)

    # 회귀 Loss (라벨이 1인 진짜 앵커들에 대해서만 좌표 오차를 계산!)
    pos_indices = (labels == 1)
    if pos_indices.sum() > 0:
        criterion_reg = nn.SmoothL1Loss()
        loss_reg = criterion_reg(pred_deltas[pos_indices], target_deltas[pos_indices])
    else:
        loss_reg = torch.tensor(0.0, device=device, requires_grad=True)

    # 분류와 회귀 Loss를 더함 (회귀 쪽에 가중치를 주는 경우도 많습니다)
    total_loss = loss_cls + (1.0 * loss_reg)

    return total_loss, loss_cls, loss_reg

# 1. 디바이스 설정
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"사용중인 디바이스: {device}")

model = MCATracker(device=device)

train_and_val(model, train_loader, val_loader, epochs=20, device=device)

import os
import cv2
import json
from tqdm import tqdm # 진행률 바를 위해 추가

def test_tracker_final(model, device, test_dir='/content/data/Anti-UAV410/test'):
    model.eval()
    save_dir = '/content/test_results'
    os.makedirs(save_dir, exist_ok=True)

    # 테스트 폴더 내의 비디오 시퀀스들을 하나씩 순회
    for seq_name in sorted(os.listdir(test_dir)):
        seq_path = os.path.join(test_dir, seq_name)
        if not os.path.isdir(seq_path): continue

        print(f"\n🚀 추적 시작: {seq_name}")
        img_files = sorted([f for f in os.listdir(seq_path) if f.lower().endswith(('.jpg', '.png'))])

        # 라벨 및 존재 여부 로드
        with open(os.path.join(seq_path, 'IR_label.json'), 'r') as f:
            label_data = json.load(f)
            gt_boxes = label_data['gt_rect']
            # 만약 exist 키가 없다면 모두 1(존재함)로 간주
            exists = label_data.get('exist', [1] * len(gt_boxes))

        # 1. 초기화 (첫 프레임)
        first_frame = cv2.imread(os.path.join(seq_path, img_files[0]))
        model.init(first_frame, gt_boxes[0])
        current_bbox = gt_boxes[0]

        # 영상 저장을 위한 준비
        h, w, _ = first_frame.shape
        out = cv2.VideoWriter(f"{save_dir}/{seq_name}.mp4", cv2.VideoWriter_fourcc(*'mp4v'), 20, (w, h))

        # 2. 순차 추적 루프 (tqdm으로 진행률 표시)
        for i in tqdm(range(len(img_files)), desc=f"Processing Frames"):
            frame = cv2.imread(os.path.join(seq_path, img_files[i]))
            if frame is None: break

            if i > 0:
                # 💡 핵심: track 실행 후 None 처리 (에러 방어막)
                result = model.track(frame, current_bbox)

                if result is None:
                    # 추적에 실패하거나 모델이 None을 뱉으면, 직전 프레임의 박스를 그대로 유지
                    pred_bbox = current_bbox
                else:
                    # 만약 모델이 (bbox, score) 형태 등 여러 개를 리턴한다면 result[0]로 수정 필요
                    pred_bbox = result

                current_bbox = pred_bbox
            else:
                pred_bbox = gt_boxes[0] # 첫 프레임은 정답 박스 사용

            # 3. 영상에 결과 그리기 (try-except로 좌표 오류 방어)
            try:
                # 🟢 모델 예측값 그리기 (녹색 두꺼운 선)
                if len(pred_bbox) >= 4:
                    px, py, pw, ph = map(int, pred_bbox[:4])
                    cv2.rectangle(frame, (px, py), (px + pw, py + ph), (0, 255, 0), 2)

                # 🔴 실제 정답(GT) 그리기 (빨간색 얇은 선) - 모델 성능 비교용!
                if i < len(gt_boxes) and exists[i] == 1:
                    gx, gy, gw, gh = map(int, gt_boxes[i])
                    cv2.rectangle(frame, (gx, gy), (gx + gw, gy + gh), (0, 0, 255), 1)
            except Exception as e:
                # 박스 좌표가 음수이거나 이상해도 코드가 뻗지 않고 그냥 넘어가게 처리
                pass

            # 프레임 번호 텍스트
            cv2.putText(frame, f"Frame: {i}", (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 255), 2)
            out.write(frame)

        out.release()
        print(f"✅ 저장 완료: /content/test_results/{seq_name}.mp4")

import torch
import os

# 1. 모델 준비 및 가중치 로드 (필요한 경우)
# 만약 학습이 끝난 가중치가 있다면 여기서 불러옵니다.
# model.load_state_dict(torch.load('best_model.pth'))

# 2. 모델을 평가 모드로 전환하고 디바이스 설정
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
model.eval()

print("🏁 테스트 및 영상 생성 시작...")

# 3. 위에서 정의한 함수 호출
# test_dir 경로가 정확한지 다시 한번 확인하세요!
test_dir_path = '/content/data/Anti-UAV410/test'

try:
    test_tracker_final(model, device, test_dir=test_dir_path)
    print("\n✨ 모든 작업이 완료되었습니다!")
except Exception as e:
    print(f"\n❌ 실행 중 에러 발생: {e}")

# 4. 생성된 영상 파일 리스트 확인
result_files = os.listdir('/content/test_results')
print(f"📁 생성된 영상 개수: {len(result_files)}개")
for f in result_files[:5]: # 상위 5개만 출력
    print(f" - {f}")